application : main.cpp imageUtils.o utils.o
	g++  -std=c++17 -o application.exe main.cpp imageUtils.o utils.o
imageUtils.o : imageUtils.cpp
	g++ -std=c++17  -c imageUtils.cpp
utils.o : utils.cpp
	g++ -std=c++17  -c utils.cpp